#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
run_grid_validation.py

Start from a single record JSON (MSON dicts) exported by your main workflow:
- 8x8 in-plane sampling (shift_a, shift_b)
- FGW scoring via RegistryPriorBO.score_registry (uses GraphEncoder + FGWScorer)
- build a relaxation pool of N points:
    * FGW-lowest low_n points
    * FGW-highest high_n points
    * mid_n uniformly sampled points from the middle-score region
- relax all N points with MACE-MP (mace_mp)
- write 3 CSVs into validation_results/:
    * relaxation_performance_stats.csv
    * proxy_energy_correlation.csv
    * energy_min_comparison.csv

Usage:
  python run_grid_validation.py \
    --record_json results/xxx_record.json \
    --embedding_path data/element_embedding.csv \
    --seed 0

Notes:
- energy_min_comparison.csv is generated by repeated resampling:
    sample K points from the relaxed pool,
    compute min(relaxed_energy), repeat S times, and store ΔE relative to
    the best relaxed energy among the FGW-lowest topK subset.
- This script now uses a deterministic low / middle-uniform / high selection
  strategy instead of random middle sampling.
"""

from __future__ import annotations

import os
import json
import argparse
import warnings
import io
import contextlib
from dataclasses import dataclass
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd

from pymatgen.core import Structure
from pymatgen.core.interface import Interface
from pymatgen.io.ase import AseAtomsAdaptor

from ase.optimize import FIRE, BFGS
from tqdm import tqdm

from regfgw.fgw_metric import FGWBuilder, FGWScorer
from regfgw.structure_to_graph import GraphEncoder
from regfgw.registry_bo import RegistryPriorBO, BOParams


@dataclass(frozen=True)
class GridPoint:
    idx: int
    shift_a: float
    shift_b: float
    fgw_score: float
    registry: Interface


def load_record_json(record_json: str) -> Dict[str, Any]:
    with open(record_json, "r", encoding="utf-8") as fr:
        meta = json.load(fr)

    required = [
        "substrate_miller", "film_miller", "termination", "cand_id", "area",
        "sub_period_layers", "film_period_layers",
        "interface", "substrate_bulk", "film_bulk"
    ]
    missing = [k for k in required if k not in meta]
    if missing:
        raise ValueError(f"Record JSON missing keys: {missing}")

    if meta["substrate_bulk"] is None or meta["film_bulk"] is None:
        raise ValueError(
            "Record JSON has substrate_bulk/film_bulk = None. "
            "Export records with build_bulk_refs=True."
        )

    rec: Dict[str, Any] = {
        "substrate_miller": tuple(int(x) for x in meta["substrate_miller"]),
        "film_miller": tuple(int(x) for x in meta["film_miller"]),
        "termination": tuple(meta["termination"]),
        "cand_id": int(meta["cand_id"]),
        "area": float(meta["area"]),
        "sub_period_layers": int(meta["sub_period_layers"]),
        "film_period_layers": int(meta["film_period_layers"]),
        "interface": Interface.from_dict(meta["interface"]),
        "substrate_bulk": Structure.from_dict(meta["substrate_bulk"]),
        "film_bulk": Structure.from_dict(meta["film_bulk"]),
    }
    return rec


def sample_low_high_mid_pool(
    finite_sorted: List[GridPoint],
    low_n: int = 8,
    high_n: int = 8,
    mid_n: int = 8,
) -> Tuple[List[GridPoint], Dict[str, int]]:
    """
    Build a fixed validation pool consisting of:
    - the lowest-score low_n points
    - the highest-score high_n points
    - mid_n uniformly sampled points from the middle-score region

    The middle-score region excludes the selected low and high tails.
    """
    low_n = int(low_n)
    high_n = int(high_n)
    mid_n = int(mid_n)
    total = low_n + high_n + mid_n

    if min(low_n, high_n, mid_n) < 0:
        raise ValueError("low_n, high_n, and mid_n must be non-negative.")

    n_finite = len(finite_sorted)
    if n_finite < total:
        raise RuntimeError(
            f"Too few finite grid points to build pool: {n_finite} < required {total}."
        )

    low_points = list(finite_sorted[:low_n]) if low_n > 0 else []
    high_points = list(finite_sorted[-high_n:]) if high_n > 0 else []

    mid_start = low_n
    mid_end = n_finite - high_n
    middle_region = finite_sorted[mid_start:mid_end]

    if mid_n > len(middle_region):
        raise RuntimeError(
            f"Middle-score region too small: need {mid_n}, have {len(middle_region)}."
        )

    if mid_n > 0:
        mid_indices = np.linspace(0, len(middle_region) - 1, mid_n, dtype=int)
        mid_points = [middle_region[i] for i in mid_indices]
    else:
        mid_indices = np.array([], dtype=int)
        mid_points = []

    pool_points = low_points + mid_points + high_points

    uniq = {(p.shift_a, p.shift_b) for p in pool_points}
    if len(uniq) != len(pool_points):
        raise RuntimeError(
            "Duplicate grid points detected in low/high/mid pool; check pool construction logic."
        )

    info = {
        "low_n": int(low_n),
        "mid_n": int(mid_n),
        "high_n": int(high_n),
        "middle_region_size": int(len(middle_region)),
        "pool_n": int(total),
    }
    return pool_points, info


def get_optimizer(name: str):
    name = name.strip().lower()
    if name == "fire":
        return FIRE
    if name == "bfgs":
        return BFGS
    raise ValueError(f"Unknown optimizer '{name}', use FIRE or BFGS.")


def make_mace_calculator(model: str, device: str, dtype: str, quiet: bool = True):
    """Create MACE-MP calculator once and reuse it. Suppress noisy load logs."""
    os.environ.pop("TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD", None)

    warnings.filterwarnings(
        "ignore",
        message=".*TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD.*",
        category=UserWarning,
    )
    warnings.filterwarnings(
        "ignore",
        message=".*Default dtype.*does not match model dtype.*",
        category=UserWarning,
    )

    from mace.calculators import mace_mp

    if not quiet:
        return mace_mp(model=model, device=device, default_dtype=dtype)

    buf_out = io.StringIO()
    buf_err = io.StringIO()
    with contextlib.redirect_stdout(buf_out), contextlib.redirect_stderr(buf_err):
        calc = mace_mp(model=model, device=device, default_dtype=dtype)
    return calc


def relax_with_mace_mp(
    itf: Interface,
    calc,
    fmax: float = 0.05,
    max_steps: int = 500,
    optimizer: str = "FIRE",
    pbar_desc: str = "relax",
) -> Tuple[float, int, bool]:
    """Relax Interface with a pre-built calculator (reuse!). Returns (E, nsteps, converged)."""
    atoms = AseAtomsAdaptor.get_atoms(itf)
    atoms.pbc = (True, True, False)
    atoms.wrap()
    atoms.calc = calc

    opt_cls = get_optimizer(optimizer)
    opt = opt_cls(atoms, logfile=None)

    step_bar = tqdm(total=int(max_steps), desc=pbar_desc, leave=False)
    last_n = {"n": 0}

    def _tick():
        n = int(getattr(opt, "nsteps", 0))
        inc = n - last_n["n"]
        if inc > 0:
            step_bar.update(inc)
            last_n["n"] = n

    opt.attach(_tick, interval=1)

    converged = False
    try:
        opt.run(fmax=float(fmax), steps=int(max_steps))
        converged = True
    except Exception:
        converged = False

    _tick()
    step_bar.close()

    energy = float(atoms.get_potential_energy())
    nsteps = int(getattr(opt, "nsteps", -1))
    return energy, nsteps, converged


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--record_json", type=str, required=True)
    ap.add_argument("--embedding_path", type=str, required=True)
    ap.add_argument("--grid_n", type=int, default=8)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out_dir", type=str, default="validation_results")

    # Pool / budget
    ap.add_argument("--budget_k", type=int, default=8, help="Budget K used for best-of-K metrics (default 8).")
    ap.add_argument("--low_n", type=int, default=8, help="Number of FGW-lowest points kept in the pool.")
    ap.add_argument("--mid_n", type=int, default=8, help="Number of uniformly sampled middle-score points kept in the pool.")
    ap.add_argument("--high_n", type=int, default=8, help="Number of FGW-highest points kept in the pool.")
    ap.add_argument("--resample_trials", type=int, default=2000,
                    help="Number of random best-of-K resampling trials (default 2000).")
    ap.add_argument("--resample_from", type=str, default="non_proxy", choices=["all", "non_proxy"],
                    help="Resample best-of-K from all pool points or only from the non-proxy pool (default non_proxy).")

    # MACE relax knobs
    ap.add_argument("--fmax", type=float, default=0.03)
    ap.add_argument("--max_steps", type=int, default=300)
    ap.add_argument("--optimizer", type=str, default="FIRE", help="FIRE or BFGS")

    # GPU / dtype
    ap.add_argument("--mace_model", type=str, default="medium")
    ap.add_argument("--mace_device", type=str, default="cuda")
    ap.add_argument("--mace_dtype", type=str, default="float32")

    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    rng = np.random.default_rng(int(args.seed))

    K = int(args.budget_k)
    low_n = int(args.low_n)
    mid_n = int(args.mid_n)
    high_n = int(args.high_n)
    N = low_n + mid_n + high_n
    if K != low_n:
        print(
            f"[WARN] budget_k={K} is not equal to low_n={low_n}. "
            f"Proxy subset will still be defined as the FGW-lowest top{K} within the pool."
        )
    if N < 2 * K:
        print(f"[WARN] pool_n={N} is < 2*budget_k={2*K}. Random baseline may be noisy.")

    # --- load record ---
    interface_rec = load_record_json(args.record_json)

    # --- init FGW stack ---
    enc = GraphEncoder(embedding_path=args.embedding_path)
    builder = FGWBuilder()
    scorer = FGWScorer(builder=builder)
    bo = RegistryPriorBO(
        encoder=enc,
        scorer=scorer,
        bo_params=BOParams(seed=int(args.seed)),
        structure_check=False,
    )

    try:
        shift_c = float(bo.suggest_shift_c(interface_rec))
    except Exception as e:
        shift_c = 0.0
        print(
            f"[WARN] suggest_shift_c_interval failed ({type(e).__name__}: {e}). "
            f"Use shift_c=0.0 Å (keep as-built gap) and continue."
        )

    # --- score all grid points ---
    n = int(args.grid_n)
    grid = np.linspace(0.0, 1.0, n, endpoint=False, dtype=float)

    points: List[GridPoint] = []
    idx = 0
    for a in grid:
        for b in grid:
            score, reg = bo.score_registry(interface_rec, shift_a=float(a), shift_b=float(b), shift_c=shift_c)
            points.append(GridPoint(idx=idx, shift_a=float(a), shift_b=float(b), fgw_score=float(score), registry=reg))
            idx += 1

    finite = [p for p in points if np.isfinite(p.fgw_score)]
    if len(finite) < N:
        raise RuntimeError(
            f"Too few finite grid points to build pool: {len(finite)} / {len(points)} < pool_n={N}."
        )

    print(f"[INFO] finite grid points: {len(finite)} / {len(points)}")

    finite_sorted = sorted(finite, key=lambda p: p.fgw_score)

    pool_points, bucket_info = sample_low_high_mid_pool(
        finite_sorted=finite_sorted,
        low_n=low_n,
        mid_n=mid_n,
        high_n=high_n,
    )
    print(
        "[INFO] low/high/mid pool: "
        f"lowest={bucket_info['low_n']}, "
        f"middle-uniform={bucket_info['mid_n']} (from {bucket_info['middle_region_size']}), "
        f"highest={bucket_info['high_n']} => N={bucket_info['pool_n']}"
    )

    pool_points_sorted = sorted(pool_points, key=lambda p: p.fgw_score)
    topK = pool_points_sorted[:K]
    non_proxy_points = pool_points_sorted[K:]
    print(f"[INFO] proxy subset within pool: lowest-score top{K}; non-proxy subset size = {len(non_proxy_points)}")

    # --- build MACE calculator once ---
    calc = make_mace_calculator(
        model=str(args.mace_model),
        device=str(args.mace_device),
        dtype=str(args.mace_dtype),
        quiet=True,
    )

    # --- relax pool points (cache by (shift_a, shift_b)) ---
    relax_cache: Dict[Tuple[float, float], Tuple[float, int, bool]] = {}

    def relax_point(p: GridPoint) -> Tuple[float, int, bool]:
        key = (p.shift_a, p.shift_b)
        if key in relax_cache:
            return relax_cache[key]
        e, steps, conv = relax_with_mace_mp(
            p.registry,
            calc=calc,
            fmax=float(args.fmax),
            max_steps=int(args.max_steps),
            optimizer=str(args.optimizer),
            pbar_desc=f"({p.shift_a:.3f},{p.shift_b:.3f})",
        )
        relax_cache[key] = (float(e), int(steps), bool(conv))
        return relax_cache[key]

    # union to avoid recompute (should be N unique, but keep safe)
    selected_keys = []
    key_to_one_point: Dict[Tuple[float, float], GridPoint] = {}
    for p in pool_points:
        k = (p.shift_a, p.shift_b)
        selected_keys.append(k)
        key_to_one_point.setdefault(k, p)
    unique_keys = sorted(set(selected_keys))

    with tqdm(total=len(unique_keys), desc="Relaxing pool registries") as outer:
        for k in unique_keys:
            p = key_to_one_point[k]
            _ = relax_point(p)
            outer.update(1)

    # --- outputs ---
    rows_perf: List[Dict[str, Any]] = []
    rows_corr: List[Dict[str, Any]] = []

    def record_row(group: str, p: GridPoint, idx_in_group: int):
        e, steps, conv = relax_cache[(p.shift_a, p.shift_b)]
        rows_perf.append({
            "group": group,
            "idx_in_group": int(idx_in_group),
            "grid_idx": int(p.idx),
            "shift_a": float(p.shift_a),
            "shift_b": float(p.shift_b),
            "shift_c": float(shift_c),
            "fgw_score": float(p.fgw_score),
            "relaxed_energy_eV": float(e),
            "relax_steps": int(steps),
            "converged": bool(conv),
        })
        rows_corr.append({
            "group": group,
            "grid_idx": int(p.idx),
            "shift_a": float(p.shift_a),
            "shift_b": float(p.shift_b),
            "shift_c": float(shift_c),
            "fgw_score": float(p.fgw_score),
            "relaxed_energy_eV": float(e),
        })

    low_key_set = {(p.shift_a, p.shift_b) for p in finite_sorted[:low_n]}
    high_key_set = {(p.shift_a, p.shift_b) for p in finite_sorted[-high_n:]} if high_n > 0 else set()
    topk_key_set = {(p.shift_a, p.shift_b) for p in topK}

    for i, p in enumerate(pool_points_sorted):
        key = (p.shift_a, p.shift_b)
        if key in topk_key_set:
            record_row(f"fgw_lowest_top{K}", p, i)
        elif key in high_key_set:
            record_row(f"fgw_highest_{high_n}", p, i)
        elif key in low_key_set:
            record_row(f"fgw_low_tail_extra_{low_n}", p, i)
        else:
            record_row(f"middle_uniform_{mid_n}", p, i)

    df_perf = pd.DataFrame(rows_perf)
    df_corr = pd.DataFrame(rows_corr)

    perf_path = os.path.join(args.out_dir, "relaxation_performance_stats.csv")
    df_perf.to_csv(perf_path, index=False)

    corr_path = os.path.join(args.out_dir, "proxy_energy_correlation.csv")
    df_corr.to_csv(corr_path, index=False)

    # --- energy_min_comparison.csv: best-of-K resampling within the pool ---
    proxy_best = float(df_perf.loc[df_perf["group"] == f"fgw_lowest_top{K}", "relaxed_energy_eV"].min())

    if str(args.resample_from).lower() == "non_proxy":
        base_df = df_perf.loc[df_perf["group"] != f"fgw_lowest_top{K}"].reset_index(drop=True)
        base_tag = f"non_proxy_{len(base_df)}"
    else:
        base_df = df_perf.reset_index(drop=True)
        base_tag = f"all_{N}"

    base_energies = base_df["relaxed_energy_eV"].to_numpy(dtype=float)
    base_size = int(base_energies.shape[0])
    if base_size < K:
        raise RuntimeError(f"Resampling base has size {base_size} < K={K}.")

    S = int(args.resample_trials)
    mins = np.empty(S, dtype=float)
    for s in range(S):
        idxs = rng.choice(base_size, size=K, replace=False)
        mins[s] = float(np.min(base_energies[idxs]))

    df_min = pd.DataFrame({
        "trial_id": np.arange(S, dtype=int),
        f"min_energy_random{K}of{base_size}_eV": mins,
        f"proxy_best_energy_top{K}_eV": np.full(S, proxy_best, dtype=float),
        "delta_random_min_minus_proxybest_eV": mins - proxy_best,
        "resample_base": np.full(S, base_tag, dtype=object),
        "pool_n": np.full(S, N, dtype=int),
        "budget_k": np.full(S, K, dtype=int),
        "seed": np.full(S, int(args.seed), dtype=int),
    })

    min_path = os.path.join(args.out_dir, "energy_min_comparison.csv")
    df_min.to_csv(min_path, index=False)

    print(f"[OK] validation_results written to: {args.out_dir}")
    print(f" - energy_min_comparison.csv (n={len(df_min)})")
    print(f" - relaxation_performance_stats.csv (n={len(df_perf)})")
    print(f" - proxy_energy_correlation.csv (n={len(df_corr)})")
    print(f"[INFO] shift_c used: {shift_c:.6f} Å")
    print(f"[INFO] pool unique relax jobs executed = {len(unique_keys)} / {N}")
    print(f"[INFO] resampling: base={base_tag}, trials={S}, K={K}")


if __name__ == "__main__":
    main()
